trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cp .env.production .env
    cat .env
    npm install
    npm run build
    npm install -g firebase-tools
    npm install
    firebase deploy --token $(firebaseToken)
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    Contents: '**/build/**' ## update to match what you want to copy
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory)